"""Increased password length to 255 from 50 as hashed strings are longer than 60

Revision ID: 843224404cef
Revises: 9bc56ee0a919
Create Date: 2025-07-13 18:35:18.738261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision: str = '843224404cef'
down_revision: Union[str, Sequence[str], None] = '9bc56ee0a919'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mssql.UNIQUEIDENTIFIER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=50, collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(collation='SQL_Latin1_General_CP1_CI_AS'), autoincrement=False, nullable=True),
    sa.Column('createdAt', sa.DATETIME(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__user__3213E83F37CC99C2'))
    )
    # ### end Alembic commands ###
