name: Deploy FastAPI to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend only
        uses: actions/checkout@v3
        with:
          sparse-checkout: |
            OP/backend
          sparse-checkout-cone-mode: false

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            cd ~/OverloadPlus
            git pull origin main
            cd OP/backend
            source venv/bin/activate
            ./deploy.sh
          EOF
